version: "2"
services:
  plone:
    image: plone:4
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/clms.addon
    environment:
      ADDONS: "clms.addon[test]"
      DEVELOP: "src/clms.addon"
